### ISSUE TITLE
How work this ?

### ISSUE THREAD

**Issue by paghapour** [jjmartres/Zabbix#154]
How to monitor a site so that if there is a problem with the site, for example, it is suspended or does not load site Let the alarm come for us

I created the application I also defined the trigger and the scenario In action, I also made a trigger, but when I suspended my site for testing, instead of an error the message could not be found and there was no notification

**Comment by pooriaaghapour** [comment]
0


How to monitor a site so that if there is a problem with the site, for example, it is suspended or does not load site Let the alarm come for us

I created the application I also defined the trigger and the scenario In action, I also made a trigger, but when I suspended my site for testing, instead of an error the message could not be found and there was no notification
